Update continuous integration yml
** travis-ci:
-Attempt to address error
"
Warning in i.p(...) :

  'lib = "/home/travis/R/Library:/usr/local/lib/R/site-library:/home/travis/R-bin/lib/R/library"' is not writable

Error: Failed to install 'rSW2utils' from GitHub:
"

** both
- added "mvtnorm" to be installed before "rSW2utils" because appveyor was failing with
"
Installing 1 packages: mvtnorm
package 'mvtnorm' successfully unpacked and MD5 sums checked
Error in i.p(...) :
  formal argument "type" matched by multiple actual arguments
Calls: <Anonymous> ... install -> safe_install_packages -> with_envvar -> force
Execution halted
Command exited with code 1
"